### ISSUE TITLE
ability to receive data form the different IPs

### ISSUE THREAD

**Issue by DukeHouse** [voronov007/basic_remote_control#1]
I can not receive nippleJS data from different IPs in local network , could you give some sggestion?

**Comment by voronov007** [comment]
I haven't worked with this repo for several years so don't know how to help you. In general, there should be a setting that allows receiving requests from different IPs. In Django it is a `ALLOW_HOSTS = ['*']` if I remember correctly.

**Comment by DukeHouse** [comment]
Thans for your reply，it works for my application！
